version: "3"

services:
  backend:
    image: backend:1
    container_name: backend
    volumes:
      - db_backup:/app/db
    ports:
      - 3421:3421
  bot:
    image: bot:1
    container_name: bot
    depends_on:
      - backend

volumes:
  db_backup: