# Generated by Django 4.2.4 on 2023-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_useraction_options_telegramuser_is_notificated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_notificated',
            field=models.BooleanField(default=False),
        ),
    ]
